export const worksData = [
    {
    id: 'forum-archive-reverie',
    title: "FORUM - ARCHIVE REVERIE",
    year: 2025,
    categories: ["Installazione Immersiva", "Web 3D", "Performance"],
    description: "Per il 55° anniversario dei Forum Studios, Archive Reverie affronta la sfida di rivitalizzare l'archivio storico, superando la logica del database statico. La visione trasforma il patrimonio dello studio in un paesaggio memoriale da esplorare liberamente, un ambiente evocativo dove frammenti sonori e visivi diventano echi di una memoria viva, incentivando la scoperta casuale e rendendo l'utente autore della propria esperienza.",
    shortDescription: "Un ecosistema interattivo che trasforma l'archivio storico dei Forum Studios in un paesaggio memoriale 3D esplorabile.",
    image: "/images/projects/forum/titolo.jpg",
    link: "/works/forum-archive-reverie",
    // MODIFICATO: heroMedia ora punta a Vimeo con il suo ID
    heroMedia: { type: 'vimeo', videoId: '1096516384' },
    technologies: [
        "React",
        "Three.js (@react-three/fiber)",
        "WebGL/GLSL",
        "Supabase (PostgreSQL)",
        "Cloudinary",
        "TouchDesigner",
        "After Effects",
        "Figma",
        "Web Audio API",
        "WebSocket"
    ],
    keyFeatures: [
        "Archivio interattivo 3D navigabile via browser.",
        "Tool di creazione visiva per generare contenuti e performance live.",
        "Video-installazione immersiva su un'unica tela visiva di 9600x1080px.",
        "Paesaggio sonoro dinamico con audio spaziale 3D (Web Audio API).",
        "Controllo remoto tramite smartphone e controller MIDI fisici (WebSocket).",
        "Workflow di sviluppo innovativo basato su co-creazione con AI."
    ],
    challenge: "La sfida principale era rivitalizzare un archivio storico superando la logica del database statico. Tecnicamente, si trattava di trattare tre superfici video non sincronizzate come un'unica, continua tela visiva, e di creare un sistema performativo e flessibile per la manipolazione dei contenuti.",
    solution: "È stato sviluppato un ecosistema interconnesso con cinque output. La soluzione centrale è una web app 3D che presenta l'archivio come una costellazione di contenuti. Un tool di creazione custom  e una pipeline di rendering offline  permettono di usare l'archivio come strumento creativo ('Archive-as-Instrument'), garantendo coerenza tra l'esperienza web, la video-installazione e le performance live.",
    figmaEmbedUrl: "https://embed.figma.com/proto/UmqXbICxnNZsk3brOajAHn/FORUM?page-id=1741%3A20&node-id=2027-126&viewport=1269%2C60631%2C0.51&scaling=min-zoom&content-scaling=fixed&embed-host=share",
    gallery: [
        { type: 'video', src: "/images/projects/forum/video1.mp4" },
        { type: 'image', src: "/images/projects/forum/1.png" },
        { type: 'image', src: "/images/projects/forum/still1.png" },
        { type: 'video', src: "/images/projects/forum/video2.mp4" },
        { type: 'image', src: "/images/projects/forum/2.png" },
        { type: 'image', src: "/images/projects/forum/still2.png" },
        { type: 'video', src: "/images/projects/forum/video3.mp4" },
        { type: 'image', src: "/images/projects/forum/3.png" },
        { type: 'image', src: "/images/projects/forum/still3.png" },
        { type: 'video', src: "/images/projects/forum/video4.mp4" },
        { type: 'image', src: "/images/projects/forum/4.png" },
        { type: 'image', src: "/images/projects/forum/still4.png" },
        
        { type: 'image', src: "/images/projects/forum/5.png" },
        { type: 'image', src: "/images/projects/forum/still5.png" },
        
        { type: 'image', src: "/images/projects/forum/6.jpg" },
        { type: 'image', src: "/images/projects/forum/7.jpg" },
        
    ]
},
{
    id: 'kollateral',
    title: "KOLLATERAL",
    year: 2025,
    categories: ["Installazione Interattiva", "Arte Audiovisiva"],
    description: "Kollateral esplora la luce come forza vitale che persiste oltre il trauma. Un telo sospeso, segnato da bruciature e lacerazioni, diventa il punto in cui questa energia si manifesta. Mosso dal suono, il tessuto si contrae e respira, diventando un corpo animato da un impulso vitale che trasforma la lacerazione in possibilità. La luce non è ostacolata dalla ferita: è proprio da lì che emerge.",
    shortDescription: "Un prototipo di installazione dove un telo lacerato, mosso dal suono, diventa un corpo che respira, lasciando emergere la luce dalle sue ferite.",
    image: "/images/cards/kollateral1.png",
    link: "/works/kollateral",
    heroMedia: { type: 'youtube', videoId: 'VYWhh3v2-LU' },
    technologies: [
        "TouchDesigner",
        "Ableton Live",
        "MIDI",
        "DMX",
        "AI (per la fase di concept)"
    ],
    keyFeatures: [
        "Un telo sospeso si anima e si muove in reazione al suono, grazie a ventilatori controllati in tempo reale.",
        "Composizione audio originale creata ad hoc che interagisce direttamente con gli elementi visivi e fisici.",
        "Integrazione tra Ableton e TouchDesigner per il controllo audio-reattivo di luci e ventilatori.",
        "Illuminazione dinamica con teste mobili controllate via DMX e integrate in TouchDesigner.",
        "Gestione delle sequenze e degli atti dell'opera tramite trigger MIDI inviati da Ableton a TouchDesigner."
    ],
    figmaEmbedUrl: "https://embed.figma.com/proto/k0GTgBcvxZax45PHgdhmGG/KOLLATERAL-%7C-SUBVIRAL?page-id=128%3A221&node-id=128-312&embed-host=share",
    challenge: "La sfida progettuale è stata quella di dare vita al concetto di un 'corpo che respira' attraverso un telo inanimato. Tecnicamente, ciò ha richiesto la creazione di una perfetta sincronia tra la composizione sonora, il movimento fisico del telo (indotto dai ventilatori) e l'illuminazione dinamica, per trasformare una lacerazione da semplice danno a un punto di passaggio per la luce.",
    solution: "È stato sviluppato un sistema integrato che collega Ableton Live a TouchDesigner. Ableton gestisce la traccia audio e l'invio di trigger MIDI per la progressione delle scene. TouchDesigner riceve i dati per controllare in tempo reale sia l'attivazione dei ventilatori che muovono il telo, sia il colore e il movimento delle luci (via DMX), creando un'esperienza immersiva e coesa dove suono, luce e materia sono indissolubilmente legati.",
    gallery: [
        
        { type: 'image', src: "/images/cards/kollateral1.png" },
        { type: 'image', src: "/images/cards/kollateral4.png" },
        { type: 'image', src: "/images/cards/kollateral2.png" },
        { type: 'image', src: "/images/cards/kollateral.png" },
        { type: 'image', src: "/images/cards/kollateral3.png" }
    ]
},

{
    id: 'symbioglitch',
    title: "VIDEOCITTÀ 2024",
    year: 2024,
    categories: ["Live Visuals", "Installazione Immersiva", "Arte Digitale"],
    description: "Symbioglitch è un'esplorazione artistica profonda del rapporto tra l'umanità e il mondo naturale. Attraverso un collage visivo e sonoro, il progetto si propone di denunciare le contraddizioni e le tensioni di questo dialogo, cercando di trasmettere emozioni complesse e stimolanti allo spettatore. Il montaggio delle immagini sarà randomico, sfruttando la casualità per creare qualcosa di unico e inaspettato, proprio come fa la natura stessa. Contrapponendo riprese di cose apparentemente distanti e non comunicanti, si creano nuovi significati e rivelazioni disturbanti sul rapporto tra l'uomo e la natura. L'estetica di 'Symbioglitch' è caratterizzata da un mix di glitch, oscurità e pessimismo. Utilizzando cambi di scena incalzanti, effetti di movimento distorti e manipolazioni visive, il progetto crea un'esperienza visiva disturbante e incerta, che mira a provocare reazioni viscerali nello spettatore. Si caratterizza per modifiche pesanti e quasi distruttive applicate ai video originali. Attraverso un processo che mira a denaturalizzare e modificare drasticamente il footage originale, si crea un effetto visivo e sonoro che sfida le percezioni convenzionali ed esplora nuove dimensioni del rapporto fra l'uomo e la natura. Questo approccio enfatizza la casualità nel montaggio delle immagini, aggiungendo un ulteriore strato di complessità e imprevedibilità alla narrazione visiva del progetto.",
    shortDescription: "Performance audiovisiva live che esplora le connessioni distorte tra umanità e natura attraverso estetiche glitch e un montaggio casuale, proiettata su una parete di 25 metri a Videocittà 2024.",
    image: "/images/projects/videocitta/still1.png",
    link: "/works/symbioglitch",
    heroMedia: { type: 'video', src: "/images/projects/videocitta/video6.mp4" },
    technologies: [
        "TouchDesigner",
        "Resolume Arena",
        "MIDI Controller",
        "Audio Reactive Systems",
        "Generative Art"
    ],
    keyFeatures: [
        "Generazione e manipolazione live di contenuti visuali tramite TouchDesigner.",
        "Projection mapping e fusione dei contenuti in tempo reale con Resolume Arena su una parete di 25 metri.",
        "Controllo interattivo dei parametri visuali tramite MIDI controller.",
        "Montaggio casuale di immagini e suoni per output unici e inaspettati.",
        "Accostamento di elementi disparati per creare nuovi significati.",
        "Esperienza visiva disturbante e incerta volta a provocare reazioni viscerali.",
        "Modifiche visive pesanti e distruttive del footage originale."
    ],
    challenge: "La sfida principale era trasmettere efficacemente le 'connessioni distorte tra umanità e natura' attraverso un'estetica di glitch, oscurità e pessimismo, richiedendo significative modifiche e un montaggio casuale degli elementi visivi e sonori per sfidare le percezioni convenzionali. Tecnicamente, l'integrazione di TouchDesigner per i visual generativi con Resolume Arena per il projection mapping su una grande parete di 25 metri, il tutto controllato in tempo reale via MIDI, ha richiesto una robusta sincronizzazione e ottimizzazione.",
    solution: "Il progetto ha utilizzato una pipeline visuale live robusta. TouchDesigner è stato impiegato per creare il contenuto visuale generativo e pesantemente modificato, che è stato poi inviato a Resolume Arena per una fusione e un projection mapping senza soluzione di continuità sulla parete di 25 metri. Il controllo in tempo reale e la manipolazione dinamica dei parametri visuali sono stati ottenuti tramite controller MIDI, consentendo una performance live fluida e reattiva. La collaborazione con sound designer ha assicurato un'esperienza audiovisiva coesa.",
    gallery: [
        { type: 'video', src: "/images/projects/videocitta/video1.mp4" },
        {type: 'image', src: "/images/cards/avperformace.jpg" },
        { type: 'video', src: "/images/projects/videocitta/video2.mp4" },
        { type: 'video', src: "/images/projects/videocitta/video3.mp4" },
        { type: 'video', src: "/images/projects/videocitta/video4.mp4" },
        { type: 'video', src: "/images/projects/videocitta/video5.mp4" },
        
    ]
},

{
    id: 'beyond-the-frame',
    title: ":BEYOND THE FRAME",
    year: 2024,
    categories: ["Installazione Interattiva", "Arte Digitale"],
    description: "Questa installazione interattiva invita lo spettatore a un viaggio sensoriale che esplora il rapporto tra percezione e distanza, giocando sul confine tra l'astratto e il riconoscibile. Ciò che da lontano appare come una texture indefinita si trasforma, avvicinandosi, in un oggetto reale che riacquista il suo contesto. È un invito a rallentare, a scoprire la bellezza nascosta nell'ordinario e a guardare oltre l'apparenza, ricordandoci che per vedere davvero, occorre fermarsi.",
    shortDescription: "Un'installazione interattiva dove la distanza dello spettatore cambia la percezione visiva, trasformando texture astratte in immagini riconoscibili.",
    image: "/images/cards/beyond2.png",
    link: "/works/beyond-the-frame",
    figmaEmbedUrl:"https://embed.figma.com/proto/0uWNVAvqtuqKGO1g3as7jJ/Beyond-the-Frame?page-id=0%3A1&node-id=0-3&embed-host=share",
    heroMedia: { type: 'image', src: "/images/projects/beyond/demo.mp4" },
    technologies: [
        "TouchDesigner",
        "Arduino",
        "Sensori di prossimità a ultrasuoni",
        "LED Wall / Proiettori"
    ],
    keyFeatures: [
        "Interazione basata sulla distanza dello spettatore, rilevata da sensori di prossimità.",
        "Transizione visiva da texture fluida a soggetto riconoscibile programmata in TouchDesigner.",
        "Concept espositivo non vincolato a uno spazio specifico, ma riproducibile e adattabile.",
        "Utilizzo di hardware specifico come sensori a ultrasuoni collegati ad Arduino per ogni opera.",
        "Possibilità di aggiungere un elemento sonoro interattivo che si lega al campo visivo dello spettatore."
    ],
    challenge: "La sfida consisteva nel creare una transizione fluida e tecnicamente stabile tra la texture astratta e il soggetto finale, basata sulla posizione esatta dello spettatore. Questo ha richiesto un'attenta fase di test e ottimizzazione per calibrare la risposta del sensore, la reattività del video e assicurare una transizione senza ritardi o scatti.",
    solution: "È stato sviluppato un sistema in TouchDesigner che gestisce l'interazione video-prossimità. Utilizzando sensori a ultrasuoni collegati ad Arduino, il sistema rileva la distanza dello spettatore e la mappa a uno specifico momento del video, che è stato post-prodotto per creare una transizione progressiva. L'installazione è stata progettata per essere modulare, utilizzando schermi o proiettori incorniciati per mantenere un'estetica fotografica.",
    gallery: [
        { type: 'image', src: "/images/cards/beyond2.png" },
        { type: 'video', src: "/images/projects/beyond/demo.mp4" },
        { type: 'video', src: "/images/projects/beyond/side1.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side1.mp4" },
        { type: 'video', src: "/images/projects/beyond/side2.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side2.mp4" },
        { type: 'video', src: "/images/projects/beyond/side3.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side3.mp4" },
        { type: 'video', src: "/images/projects/beyond/side4.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side4.mp4" },
        { type: 'video', src: "/images/projects/beyond/side5.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side5.mp4" },
        { type: 'video', src: "/images/projects/beyond/side6.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side6.mp4" },

    ]
},


// --- NUOVI PROGETTI DA COMPILARE ---
{
    id: 'bmw-reignite-the-pleasure',
    title: 'BMW - RE:IGNITE THE PLEASURE',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/projects/bmw/hero.png',
    link: '/works/bmw-reignite-the-pleasure',
    heroMedia: { type: 'image', src: '/images/projects/bmw/hero.png' },
    technologies: ['Tecnologia 1'],
    figmaEmbedUrl:"https://embed.figma.com/proto/VJKiZCYc869sU3yl3mW5a0/BMW?page-id=370%3A249&node-id=286-8&scaling=min-zoom&content-scaling=fixed&embed-host=share",
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [
        { type: 'image', src: '/images/projects/bmw/ooh.png' },
        { type: 'video', src: '/images/projects/bmw/scroll.mp4' },
        { type: 'video', src: '/images/projects/bmw/landing.mp4' },
        { type: 'image', src: '/images/projects/bmw/hero.png' },

        { type: 'video', src: '/images/projects/bmw/scroll.mp4' },
        { type: 'video', src: '/images/projects/bmw/story.mp4' }
    ]
},
{
    id: 'circularthub',
    title: 'CIRCULARTHUB',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/circularthub.png',
    link: '/works/circularthub',
    heroMedia: { type: 'image', src: '/images/hero/circularthub.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    figmaEmbedUrl:"https://embed.figma.com/proto/0uWNVAvqtuqKGO1g3as7jJ/Beyond-the-Frame?page-id=0%3A1&node-id=0-3&embed-host=share",
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/circularthub/1.png' }]
},
{
    id: 'haizum',
    title: 'HAIZUM',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/haizum.png',
    link: '/works/haizum',
    heroMedia: { type: 'image', src: '/images/hero/haizum.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/haizum/1.png' }]
},
{
    id: 'il-viaggio-nel-linguaggio',
    title: 'IL VIAGGIO NEL LINGUAGGIO',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/il-viaggio-nel-linguaggio.png',
    link: '/works/il-viaggio-nel-linguaggio',
    heroMedia: { type: 'image', src: '/images/hero/il-viaggio-nel-linguaggio.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/il-viaggio-nel-linguaggio/1.png' }]
},
{
    id: 'rxink-personal-brand',
    title: 'RXINK - PERSONAL BRAND',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/projects/rxink/pattern.png',
    link: '/works/rxink-personal-brand',
    heroMedia: { type: 'image', src: '/images/projects/rxink/construction.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    figmaEmbedUrl:"https://embed.figma.com/proto/bCQ5r2B4hhs3sL12B7zodE/Untitled?page-id=120%3A1332&node-id=120-1333&starting-point-node-id=120%3A1333&scaling=scale-down&content-scaling=fixed&embed-host=share",
    gallery: [{ type: 'image', src: '/images/projects/rxink/black.png' },
        { type: 'video', src: '/images/projects/rxink/LOGOANIMATION10.mp4' },
        { type: 'image', src: '/images/projects/rxink/green.png' },
        { type: 'image', src: '/images/projects/rxink/pattern.png' },
        { type: 'image', src: '/images/projects/rxink/think.png' },
        { type: 'video', src: '/images/projects/rxink/logoanimationverticale.mp4' },
        { type: 'image', src: '/images/projects/rxink/yellow1.png' },
        { type: 'image', src: '/images/projects/rxink/BannerLinkedin.png' }
    ]
},
{
    id: 'trashfinder',
    title: 'TRASHFINDER',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/trashfinder.png',
    link: '/works/trashfinder',
    heroMedia: { type: 'image', src: '/images/hero/trashfinder.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/trashfinder/1.png' }]
},
{
    id: 'videocitta-2024',
    title: 'VIDEOCITTA 2024',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/videocitta-2024.png',
    link: '/works/videocitta-2024',
    heroMedia: { type: 'image', src: '/images/hero/videocitta-2024.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/videocitta-2024/1.png' }]
},
{
    id: 'vinted-non-mi-metti',
    title: 'VINTED - NON MI METTI?',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/vinted-non-mi-metti.png',
    link: '/works/vinted-non-mi-metti',
    heroMedia: { type: 'youtube', videoId: 'y5pSa9Mp-qg' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    figmaEmbedUrl:"https://embed.figma.com/proto/7mD2tcVCpDlpjDgzdq7nXy/Vinted?page-id=191%3A65&node-id=232-139&embed-host=share",
    gallery: [{ type: 'image', src: '/images/gallery/vinted-non-mi-metti/1.png' }]
},
{
    id: 'algorithmube',
    title: 'ALGORITHMUBE',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/algorithmube.png',
    link: '/works/algorithmube',
    heroMedia: { type: 'image', src: '/images/hero/algorithmube.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/algorithmube/1.png' }]
},
{
    id: 'friends-in-my-head',
    title: 'FRIENDS IN MY HEAD',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/projects/friendsinmyhead/still4.png',
    link: '/works/friends-in-my-head',
    heroMedia: { type: 'vimeo', videoId: '1097622993' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/projects/friendsinmyhead/still1.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still2.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still3.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still4.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still5.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still6.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still7.png' }
    ]
},
{
    id: 'one-of-these-days',
    title: 'ONE OF THESE DAYS',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/one-of-these-days.png',
    link: '/works/one-of-these-days',
    heroMedia: { type: 'youtube', videoId: 'AmHK1_hq3cQ' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/one-of-these-days/1.png' }]
},
{
    id: 'roma-crater-mundi',
    title: 'ROMA CRATER MUNDI',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/projects/romacratermundi/titolo.png',
    link: '/works/roma-crater-mundi',
    heroMedia: { type: 'image', src:'/images/projects/romacratermundi/titolo.png'},
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/projects/romacratermundi/still1.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still2.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still3.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still4.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still5.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still6.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still7.png' }
    ]
},
{
    id: 'subviral',
    title: 'SUBVIRAL',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/subviral.png',
    link: '/works/subviral',
    heroMedia: { type: 'vimeo', videoId: '1093522831' },
    figmaEmbedUrl: "https://embed.figma.com/proto/k0GTgBcvxZax45PHgdhmGG/KOLLATERAL-%7C-SUBVIRAL?page-id=186%3A115&node-id=186-353&viewport=482%2C221%2C0.18&scaling=contain&content-scaling=fixed&embed-host=share",
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/subviral/1.png' }]
},
{
    id: 'templarave',
    title: 'TEMPLARAVE',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/templarave.png',
    link: '/works/templarave',
    heroMedia: { type: 'image', src: '/images/hero/templarave.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/templarave/1.png' }]
},
{
    id: 'topology-of-decay',
    title: 'TOPOLOGY OF DECAY',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/topology-of-decay.png',
    link: '/works/topology-of-decay',
    heroMedia: { type: 'image', src: '/images/hero/topology-of-decay.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/topology-of-decay/1.png' }]
},
{
    id: 'y2kmush',
    title: 'Y2KMUSH',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/y2kmush.png',
    link: '/works/y2kmush',
    heroMedia: { type: 'image', src: '/images/hero/y2kmush.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/y2kmush/1.png' }]
}
];

// Function to get a work by its ID
export function getWorkById(id) {
    return worksData.find(work => work.id === id);
}