export const worksData = [
    {
    id: 'forum-archive-reverie',
    title: "FORUM - ARCHIVE REVERIE",
    year: 2025,
    categories: ['Installazione Interattiva & Artistica', 'Sviluppo Web & UI/UX', 'Direzione Creativa & Art Direction'],
    description: "Per il 55° anniversario dei Forum Studios, Archive Reverie affronta la sfida di rivitalizzare l'archivio storico, superando la logica del database statico. La visione trasforma il patrimonio dello studio in un paesaggio memoriale da esplorare liberamente, un ambiente evocativo dove frammenti sonori e visivi diventano echi di una memoria viva, incentivando la scoperta casuale e rendendo l'utente autore della propria esperienza.",
    shortDescription: "Un ecosistema interattivo che trasforma l'archivio storico dei Forum Studios in un paesaggio memoriale 3D esplorabile.",
    image: "/images/projects/forum/titolo.jpg",
    link: "/works/forum-archive-reverie",
    heroMedia: { type: 'vimeo', videoId: '1096516384' },
    technologies: [
        "React",
        "Three.js (@react-three/fiber)",
        "WebGL/GLSL",
        "Supabase (PostgreSQL)",
        "Cloudinary",
        "TouchDesigner",
        "After Effects",
        "Figma",
        "Web Audio API",
        "WebSocket"
    ],
    keyFeatures: [
        "Archivio interattivo 3D navigabile via browser.",
        "Tool di creazione visiva per generare contenuti e performance live.",
        "Video-installazione immersiva su un'unica tela visiva di 9600x1080px.",
        "Paesaggio sonoro dinamico con audio spaziale 3D (Web Audio API).",
        "Controllo remoto tramite smartphone e controller MIDI fisici (WebSocket).",
        "Workflow di sviluppo innovativo basato su co-creazione con AI."
    ],
    challenge: "La sfida principale era rivitalizzare un archivio storico superando la logica del database statico. Tecnicamente, si trattava di trattare tre superfici video non sincronizzate come un'unica, continua tela visiva, e di creare un sistema performativo e flessibile per la manipolazione dei contenuti.",
    solution: "È stato sviluppato un ecosistema interconnesso con cinque output. La soluzione centrale è una web app 3D che presenta l'archivio come una costellazione di contenuti. Un tool di creazione custom  e una pipeline di rendering offline  permettono di usare l'archivio come strumento creativo ('Archive-as-Instrument'), garantendo coerenza tra l'esperienza web, la video-installazione e le performance live.",
    figmaEmbedUrl: "https://embed.figma.com/proto/UmqXbICxnNZsk3brOajAHn/FORUM?page-id=1741%3A20&node-id=2027-126&viewport=1269%2C60631%2C0.51&scaling=min-zoom&content-scaling=fixed&embed-host=share",
    gallery: [
        { type: 'video', src: "/images/projects/forum/video1.mp4" },
        { type: 'image', src: "/images/projects/forum/1.png" },
        { type: 'image', src: "/images/projects/forum/still1.png" },
        { type: 'video', src: "/images/projects/forum/video2.mp4" },
        { type: 'image', src: "/images/projects/forum/2.png" },
        { type: 'image', src: "/images/projects/forum/still2.png" },
        { type: 'video', src: "/images/projects/forum/video3.mp4" },
        { type: 'image', src: "/images/projects/forum/3.png" },
        { type: 'image', src: "/images/projects/forum/still3.png" },
        { type: 'video', src: "/images/projects/forum/video4.mp4" },
        { type: 'image', src: "/images/projects/forum/4.png" },
        { type: 'image', src: "/images/projects/forum/still4.png" },
        { type: 'image', src: "/images/projects/forum/5.png" },
        { type: 'image', src: "/images/projects/forum/still5.png" },
        { type: 'image', src: "/images/projects/forum/6.jpg" },
        { type: 'image', src: "/images/projects/forum/7.jpg" },
    ]
},

{
    id: 'vinted-non-mi-metti',
    title: 'VINTED - NON MI METTI?',
    year: 2025,
    categories: ['Campagna Pubblicitaria', 'Direzione Creativa & Art Direction'],
    description: 'Il progetto ribalta il punto di vista delle classiche campagne Vinted, spostando l’attenzione da chi vende a ciò che viene lasciato indietro. Attraverso un approccio affettuoso, ironico e leggermente malinconico, il capo d\'abbigliamento viene umanizzato, creando una connessione emotiva con lo spettatore. Il vestito non è solo un oggetto, ma un protagonista invisibile che attende di tornare a vivere. Per rendere questo sguardo visibile, la regia adotta l’object POV: la camera è nascosta nell’armadio, trasformando lo sguardo del vestito in una testimonianza intima e silenziosa.',
    shortDescription: 'La campagna "Non mi metti?" ribalta il punto di vista delle classiche campagne Vinted, umanizzando un capo d’abbigliamento dimenticato per creare una forte connessione emotiva.',
    image: '/images/projects/vinted/card.png',
    link: '/works/vinted-non-mi-metti',
    heroMedia: { type: 'youtube', videoId: 'y5pSa9Mp-qg' },
    technologies: ['Adobe Premiere Pro', 'Adobe After Effects', 'Figma', 'Photoshop', 'Sony A7S II'],
    keyFeatures: [
        "Regia creativa basata sull'object point-of-view (POV).",
        "Copywriting emotivo e ironico per umanizzare il prodotto.",
        "Direzione completa del progetto: dallo script al montaggio finale.",
        "Creazione di una narrazione malinconica e affettuosa.",
        "Sviluppo del concept di comunicazione della campagna."
    ],
    challenge: 'La sfida era distinguersi dalle tipiche campagne Vinted, incentrate sul venditore. L\'obiettivo era creare una narrazione originale e memorabile, capace di generare un legame emotivo con il pubblico attraverso l\'insolita prospettiva di un oggetto inanimato.',
    solution: 'Spostando il focus narrativo sul vestito stesso, la campagna ha acquisito un tono unico. L\'uso dell\'object POV, unito a un copywriting che mescola ironia e malinconia, ha permesso di raccontare una storia universale di abbandono e desiderio, trasformando un semplice annuncio di vendita in un piccolo racconto emotivo.',
    figmaEmbedUrl: "https://embed.figma.com/proto/bCQ5r2B4hhs3sL12B7zodE/Untitled?page-id=213%3A2&node-id=213-303&viewport=384%2C172%2C0.02&scaling=contain&content-scaling=fixed&embed-host=share",
    gallery: [{ type: 'image', src: '/images/projects/vinted/card.png' },
        { type: 'image', src: '/images/projects/vinted/1.png' },
        { type: 'image', src: '/images/projects/vinted/2.png' },
        { type: 'image', src: '/images/projects/vinted/3.png' },
        { type: 'image', src: '/images/projects/vinted/4.png' },
        { type: 'image', src: '/images/projects/vinted/5.png' },
        { type: 'image', src: '/images/projects/vinted/6.png' }
    ]
},
{
    id: 'rxink-personal-brand',
    title: 'RXINK - PERSONAL BRAND',
    year: 2024,
    categories: ['Branding & Identità Visiva', 'Motion Design'],
    description: 'RXINK è il mio brandbook personale, un caso studio di branding dove ogni aspetto dell\'identità visiva è stato esplorato in profondità. Il progetto include la progettazione del logo e del pittogramma, la definizione della palette colori, la scelta dei font, e lo sviluppo di animazioni del logo e di elementi di motion design che definiscono il linguaggio visivo del brand.',
    shortDescription: 'Progetto di branding personale completo, che definisce ogni aspetto dell\'identità visiva del brand RXINK, dal logo alla motion graphics.',
    image: '/images/projects/rxink/pattern.png',
    link: '/works/rxink-personal-brand',
    heroMedia: { type: 'image', src: '/images/projects/rxink/construction.png' },
    technologies: ['Adobe Illustrator', 'Adobe After Effects', 'Figma'],
    keyFeatures: [
        'Design del logo, pittogramma e sistema di identità visiva.',
        'Definizione della palette colori e della tipografia.',
        'Creazione di logo animation e motion graphics.',
        'Sviluppo di un brandbook completo e coerente.',
        'Applicazione del brand su vari touchpoint digitali.'
    ],
    challenge: 'La sfida era creare un\'identità di brand personale che fosse versatile, riconoscibile e rappresentativa delle mie competenze nel campo del design e della motion graphics, evitando cliché e creando un linguaggio visivo unico.',
    solution: 'Ho sviluppato un sistema di branding modulare basato su un logo forte e un pittogramma versatile. L\'uso strategico del colore e della motion graphics permette al brand di adattarsi a contesti diversi, mantenendo sempre una forte coerenza e riconoscibilità.',
    figmaEmbedUrl:"https://embed.figma.com/proto/bCQ5r2B4hhs3sL12B7zodE/Untitled?page-id=120%3A1332&node-id=120-1333&starting-point-node-id=120%3A1333&scaling=scale-down&content-scaling=fixed&embed-host=share",
    gallery: [{ type: 'image', src: '/images/projects/rxink/black.png' },
        { type: 'video', src: '/images/projects/rxink/LOGOANIMATION10.mp4' },
        { type: 'image', src: '/images/projects/rxink/green.png' },
        { type: 'image', src: '/images/projects/rxink/pattern.png' },
        { type: 'image', src: '/images/projects/rxink/think.png' },
        { type: 'video', src: '/images/projects/rxink/logoanimationverticale.mp4' },
        { type: 'image', src: '/images/projects/rxink/yellow1.png' },
        { type: 'image', src: '/images/projects/rxink/BannerLinkedin.png' }
    ]
},
{
    id: 'kollateral',
    title: "KOLLATERAL",
    year: 2025,
    categories: ['Installazione Interattiva & Artistica'],
    description: "Kollateral esplora la luce come forza vitale che persiste oltre il trauma. Un telo sospeso, segnato da bruciature e lacerazioni, diventa il punto in cui questa energia si manifesta. Mosso dal suono, il tessuto si contrae e respira, diventando un corpo animato da un impulso vitale che trasforma la lacerazione in possibilità. La luce non è ostacolata dalla ferita: è proprio da lì che emerge.",
    shortDescription: "Un prototipo di installazione dove un telo lacerato, mosso dal suono, diventa un corpo che respira, lasciando emergere la luce dalle sue ferite.",
    image: "/images/cards/kollateral1.png",
    link: "/works/kollateral",
    heroMedia: { type: 'youtube', videoId: 'VYWhh3v2-LU' },
    technologies: [
        "TouchDesigner",
        "Ableton Live",
        "MIDI",
        "DMX",
        "AI (per la fase di concept)"
    ],
    keyFeatures: [
        "Un telo sospeso si anima e si muove in reazione al suono, grazie a ventilatori controllati in tempo reale.",
        "Composizione audio originale creata ad hoc che interagisce direttamente con gli elementi visivi e fisici.",
        "Integrazione tra Ableton e TouchDesigner per il controllo audio-reattivo di luci e ventilatori.",
        "Illuminazione dinamica con teste mobili controllate via DMX e integrate in TouchDesigner.",
        "Gestione delle sequenze e degli atti dell'opera tramite trigger MIDI inviati da Ableton a TouchDesigner."
    ],
    figmaEmbedUrl: "https://embed.figma.com/proto/k0GTgBcvxZax45PHgdhmGG/KOLLATERAL-%7C-SUBVIRAL?page-id=128%3A221&node-id=128-312&embed-host=share",
    challenge: "La sfida progettuale è stata quella di dare vita al concetto di un 'corpo che respira' attraverso un telo inanimato. Tecnicamente, ciò ha richiesto la creazione di una perfetta sincronia tra la composizione sonora, il movimento fisico del telo (indotto dai ventilatori) e l'illuminazione dinamica, per trasformare una lacerazione da semplice danno a un punto di passaggio per la luce.",
    solution: "È stato sviluppato un sistema integrato che collega Ableton Live a TouchDesigner. Ableton gestisce la traccia audio e l'invio di trigger MIDI per la progressione delle scene. TouchDesigner riceve i dati per controllare in tempo reale sia l'attivazione dei ventilatori che muovono il telo, sia il colore e il movimento delle luci (via DMX), creando un'esperienza immersiva e coesa dove suono, luce e materia sono indissolubilmente legati.",
    gallery: [
        
        { type: 'image', src: "/images/cards/kollateral1.png" },
        { type: 'image', src: "/images/cards/kollateral4.png" },
        { type: 'image', src: "/images/cards/kollateral2.png" },
        { type: 'image', src: "/images/cards/kollateral.png" },
        { type: 'image', src: "/images/cards/kollateral3.png" }
    ]
},

{
    id: 'bmw-reignite-the-pleasure',
    title: 'BMW - RE:IGNITE THE PLEASURE',
    year: 2025,
    categories: ['Campagna Pubblicitaria', 'Sviluppo Web & UI/UX', 'Direzione Creativa & Art Direction'],
    description: 'Questa campagna cross-platform riporta in vita un\'icona degli anni \'80, la BMW M3 E30, per venderla al pubblico di oggi. Sfruttando il gioco di parole "RE:" (RE:IGNITE, RE:DISCOVER), la comunicazione crea una forte connessione emotiva evocando momenti di vita condivisi. Il fulcro è un sito web interattivo con una landing page, una sezione con un render 3D animato dell\'auto, una timeline che ripercorre le tappe della vita, e una pagina di vendita per un\'ipotetica riedizione elettrica del veicolo.',
    shortDescription: 'Campagna cross-platform che reinterpreta l\'iconica BMW M3 E30 per il pubblico moderno, combinando storytelling emotivo e un\'esperienza web interattiva.',
    image: '/images/projects/bmw/hero.png',
    link: '/works/bmw-reignite-the-pleasure',
    heroMedia: { type: 'image', src: '/images/projects/bmw/hero.png' },
    technologies: ['Svelte', 'JavaScript', 'Blender', 'Adobe After Effects', 'Adobe Illustrator', 'Figma', 'Photoshop'],
    figmaEmbedUrl:"https://embed.figma.com/proto/VJKiZCYc869sU3yl3mW5a0/BMW?page-id=370%3A249&node-id=286-8&scaling=min-zoom&content-scaling=fixed&embed-host=share",
    keyFeatures: [
        'Concept di campagna cross-platform basato su storytelling emotivo.',
        'Sito web interattivo sviluppato in Svelte e JavaScript.',
        'Animazione 3D di un modello di auto renderizzato in Blender.',
        'Copywriting creativo basato sul gioco di parole "RE:".',
        'Timeline interattiva per esplorare la storia del brand e dell\'utente.'
    ],
    challenge: 'La sfida era rendere nuovamente desiderabile un\'icona del passato per un pubblico contemporaneo, bilanciando nostalgia e innovazione. Tecnicamente, l\'obiettivo era integrare un\'esperienza 3D fluida all\'interno di un sito web performante e sviluppare una narrazione coinvolgente su più canali.',
    solution: 'Attraverso uno storytelling che fa leva su ricordi universali, la campagna crea un ponte emotivo tra passato e presente. Il sito web funge da hub centrale dell\'esperienza, combinando un design moderno con tecnologie interattive come un render 3D esplorabile, per presentare il concept di una E30 elettrica come l\'evoluzione naturale di un mito.',
    gallery: [
        { type: 'image', src: '/images/projects/bmw/ooh.png' },
        { type: 'video', src: '/images/projects/bmw/scroll.mp4' },
        { type: 'video', src: '/images/projects/bmw/landing.mp4' },
        { type: 'image', src: '/images/projects/bmw/hero.png' },
        { type: 'video', src: '/images/projects/bmw/scroll.mp4' },
        { type: 'video', src: '/images/projects/bmw/story.mp4' }
    ]
},

{
    id: 'symbioglitch',
    title: "VIDEOCITTÀ 2024",
    year: 2024,
    categories: ['Installazione Interattiva & Artistica', 'Live Visuals'],
    description: "Symbioglitch esplora il rapporto conflittuale tra umanità e natura attraverso un'estetica glitch e oscura. La performance audiovisiva, proiettata su una parete di 25 metri per Videocittà 2024, utilizza un montaggio casuale e una manipolazione quasi distruttiva del footage per creare un'esperienza visiva disturbante e stimolare reazioni viscerali. Accostando elementi visivi e sonori apparentemente distanti, l'opera genera nuovi e inquietanti significati su questa complessa relazione.",
    shortDescription: "Performance audiovisiva live che esplora le connessioni distorte tra umanità e natura attraverso estetiche glitch e un montaggio casuale, proiettata su una parete di 25 metri a Videocittà 2024.",
    image: "/images/projects/videocitta/hero.png",
    link: "/works/symbioglitch",
    heroMedia: { type: 'video', src: "/images/projects/videocitta/video6.mp4" },
    technologies: [
        "TouchDesigner",
        "Resolume Arena",
        "MIDI Controller",
        "Audio Reactive Systems",
        "Generative Art"
    ],
    keyFeatures: [
        "Generazione e manipolazione live di contenuti visuali tramite TouchDesigner.",
        "Projection mapping e fusione dei contenuti in tempo reale con Resolume Arena su una parete di 25 metri.",
        "Controllo interattivo dei parametri visuali tramite MIDI controller.",
        "Montaggio casuale di immagini e suoni per output unici e inaspettati.",
        "Accostamento di elementi disparati per creare nuovi significati.",
        "Esperienza visiva disturbante e incerta volta a provocare reazioni viscerali.",
        "Modifiche visive pesanti e distruttive del footage originale."
    ],
    challenge: "La sfida principale era trasmettere efficacemente le 'connessioni distorte tra umanità e natura' attraverso un'estetica di glitch, oscurità e pessimismo, richiedendo significative modifiche e un montaggio casuale degli elementi visivi e sonori per sfidare le percezioni convenzionali. Tecnicamente, l'integrazione di TouchDesigner per i visual generativi con Resolume Arena per il projection mapping su una grande parete di 25 metri, il tutto controllato in tempo reale via MIDI, ha richiesto una robusta sincronizzazione e ottimizzazione.",
    solution: "Il progetto ha utilizzato una pipeline visuale live robusta. TouchDesigner è stato impiegato per creare il contenuto visuale generativo e pesantemente modificato, che è stato poi inviato a Resolume Arena per una fusione e un projection mapping senza soluzione di continuità sulla parete di 25 metri. Il controllo in tempo reale e la manipolazione dinamica dei parametri visuali sono stati ottenuti tramite controller MIDI, consentendo una performance live fluida e reattiva. La collaborazione con sound designer ha assicurato un'esperienza audiovisiva coesa.",
    gallery: [
        { type: 'video', src: "/images/projects/videocitta/video1.mp4" },
        {type: 'image', src: "/images/cards/avperformace.jpg" },
        { type: 'video', src: "/images/projects/videocitta/video2.mp4" },
        { type: 'video', src: "/images/projects/videocitta/video3.mp4" },
        { type: 'video', src: "/images/projects/videocitta/video4.mp4" },
        { type: 'video', src: "/images/projects/videocitta/video5.mp4" },
    ]
},

{
    id: 'beyond-the-frame',
    title: ":BEYOND THE FRAME",
    year: 2024,
    categories: ['Installazione Interattiva & Artistica'],
    description: "Questa installazione interattiva invita lo spettatore a un viaggio sensoriale che esplora il rapporto tra percezione e distanza, giocando sul confine tra l'astratto e il riconoscibile. Ciò che da lontano appare come una texture indefinita si trasforma, avvicinandosi, in un oggetto reale che riacquista il suo contesto. È un invito a rallentare, a scoprire la bellezza nascosta nell'ordinario e a guardare oltre l'apparenza, ricordandoci che per vedere davvero, occorre fermarsi.",
    shortDescription: "Un'installazione interattiva dove la distanza dello spettatore cambia la percezione visiva, trasformando texture astratte in immagini riconoscibili.",
    image: "/images/cards/beyond2.png",
    link: "/works/beyond-the-frame",
    figmaEmbedUrl:"https://embed.figma.com/proto/0uWNVAvqtuqKGO1g3as7jJ/Beyond-the-Frame?page-id=0%3A1&node-id=0-3&embed-host=share",
    heroMedia: { type: 'image', src: "/images/projects/beyond/demo.mp4" },
    technologies: [
        "TouchDesigner",
        "Arduino",
        "Sensori di prossimità a ultrasuoni",
        "LED Wall / Proiettori"
    ],
    keyFeatures: [
        "Interazione basata sulla distanza dello spettatore, rilevata da sensori di prossimità.",
        "Transizione visiva da texture fluida a soggetto riconoscibile programmata in TouchDesigner.",
        "Concept espositivo non vincolato a uno spazio specifico, ma riproducibile e adattabile.",
        "Utilizzo di hardware specifico come sensori a ultrasuoni collegati ad Arduino per ogni opera.",
        "Possibilità di aggiungere un elemento sonoro interattivo che si lega al campo visivo dello spettatore."
    ],
    challenge: "La sfida consisteva nel creare una transizione fluida e tecnicamente stabile tra la texture astratta e il soggetto finale, basata sulla posizione esatta dello spettatore. Questo ha richiesto un'attenta fase di test e ottimizzazione per calibrare la risposta del sensore, la reattività del video e assicurare una transizione senza ritardi o scatti.",
    solution: "È stato sviluppato un sistema in TouchDesigner che gestisce l'interazione video-prossimità. Utilizzando sensori a ultrasuoni collegati ad Arduino, il sistema rileva la distanza dello spettatore e la mappa a uno specifico momento del video, che è stato post-prodotto per creare una transizione progressiva. L'installazione è stata progettata per essere modulare, utilizzando schermi o proiettori incorniciati per mantenere un'estetica fotografica.",
    gallery: [
        { type: 'image', src: "/images/cards/beyond2.png" },
        { type: 'video', src: "/images/projects/beyond/demo.mp4" },
        { type: 'video', src: "/images/projects/beyond/side1.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side1.mp4" },
        { type: 'video', src: "/images/projects/beyond/side2.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side2.mp4" },
        { type: 'video', src: "/images/projects/beyond/side3.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side3.mp4" },
        { type: 'video', src: "/images/projects/beyond/side4.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side4.mp4" },
        { type: 'video', src: "/images/projects/beyond/side5.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side5.mp4" },
        { type: 'video', src: "/images/projects/beyond/side6.mp4" },
        { type: 'video', src: "/images/projects/beyond/_side6.mp4" },
    ]
},

{
    id: 'circularthub',
    title: 'CIRCULARTHUB',
    year: 2024,
    categories: ['Sviluppo Web & UI/UX', 'Branding & Identità Visiva'],
    description: 'CirculArtHub è una piattaforma digitale progettata per la vendita di prodotti artistici e di design realizzati con materiali di recupero (upcycling). Il progetto include la creazione completa della brand identity, la pianificazione della user journey (platform action chart) e la prototipazione di tutte le schermate e della navigabilità su Figma. L\'obiettivo è incentivare l\'economia circolare, lo scambio a mano e dare visibilità ad artisti e designer emergenti che lavorano con il riutilizzo creativo.',
    shortDescription: 'Piattaforma digitale per la vendita di prodotti upcycled, completa di brand identity, UI/UX e prototipo navigabile.',
    image: '/images/projects/circularthub/card.png',
    link: '/works/circularthub',
    heroMedia: { type: 'image', src: '/images/projects/circularthub/hero.png' },
    technologies: ['Figma', 'Adobe Illustrator'],
    keyFeatures: [
        'Creazione della brand identity (logo, colori, tipografia).',
        'Progettazione dell\'interfaccia utente (UI) e dell\'esperienza utente (UX).',
        'Sviluppo di un prototipo interattivo e navigabile in Figma.',
        'Definizione della logica della piattaforma e delle interazioni.',
        'Focus su sostenibilità, riutilizzo e supporto alla comunità artistica.'
    ],
    figmaEmbedUrl: "https://embed.figma.com/proto/DUOOxYSzLFFt4C49mpZXUK/CirculArtHub_RxInK?page-id=&node-id=418-372&viewport=-27%2C-97%2C0.02&scaling=contain&content-scaling=fixed&embed-host=share",
    challenge: 'La sfida principale era progettare un\'interfaccia che fosse allo stesso tempo esteticamente piacevole, intuitiva per artisti e compratori, e capace di comunicare in modo efficace i valori di sostenibilità e unicità dei prodotti venduti.',
    solution: 'È stato sviluppato un design pulito e moderno, che mette in risalto le immagini dei prodotti. La navigazione è stata semplificata per facilitare la scoperta di nuovi artisti e l\'acquisto. Il prototipo in Figma ha permesso di testare e validare il flusso utente prima dello sviluppo, assicurando un\'esperienza utente coesa e funzionale.',
    gallery: [{ type: 'image', src: '/images/projects/circularthub/1.png' },
        { type: 'image', src: '/images/projects/circularthub/2.png' },
        { type: 'image', src: '/images/projects/circularthub/3.png' },
        { type: 'image', src: '/images/projects/circularthub/4.png' },
        { type: 'image', src: '/images/projects/circularthub/5.png' },
        { type: 'image', src: '/images/projects/circularthub/6.png' },
        { type: 'image', src: '/images/projects/circularthub/7.png' },
        { type: 'image', src: '/images/projects/circularthub/card.png' }
    ]
},

{
    id: 'roma-crater-mundi',
    title: 'ROMA CRATER MUNDI',
    year: 2024,
    categories: ['Fotografia', 'Direzione Creativa & Art Direction'],
    description: '"Roma Crater Mundi" è un progetto artistico e fotografico che trasforma un noto problema urbano, le buche di Roma, in un soggetto di inaspettata bellezza. Attraverso lo sguardo fotografico, le crepe e le voragini nell\'asfalto vengono decontestualizzate e immortalate come paesaggi lunari o crateri astratti, invitando a una riflessione sulla resilienza e sulla capacità di trovare valore estetico anche nel degrado. Il progetto è stato completato con l\'impaginazione di un libro fotografico in InDesign e la stampa su carta di alta qualità.',
    shortDescription: 'Un progetto fotografico che nobilita le buche di Roma, trasformandole in crateri astratti e paesaggi inaspettati.',
    image: '/images/projects/romacratermundi/card.jpg',
    link: '/works/roma-crater-mundi',
    heroMedia: { type: 'image', src:'/images/projects/romacratermundi/hero.jpg'},
    technologies: ['Fotografia Digitale (Canon 700D)', 'Adobe InDesign', 'Adobe Photoshop'],
    keyFeatures: [
        'Concept artistico che valorizza elementi del degrado urbano.',
        'Serie fotografica con uno stile visivo coerente.',
        'Progettazione e impaginazione di un libro fotografico.',
        'Stampa finale su carta fotografica per esaltare i dettagli.',
        'Ricerca estetica sulla texture e la composizione astratta.'
    ],
    challenge: 'La sfida era elevare un soggetto comunemente associato a disagio e degrado, come le buche stradali, a un livello artistico, trovando angolazioni, luci e composizioni capaci di rivelarne una bellezza nascosta e astratta.',
    solution: 'Attraverso un attento lavoro di composizione e post-produzione, ogni buca è stata trattata come un paesaggio a sé stante. L\'impaginazione del libro fotografico ha permesso di creare una narrazione visiva sequenziale, guidando lo spettatore in un viaggio attraverso questi "crateri urbani" e consolidando il concept del progetto.',
    gallery: [{ type: 'image', src: '/images/projects/romacratermundi/still1.png' },
        { type: 'image', src: '/images/projects/romacratermundi/1.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/2.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/3.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/4.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/5.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/6.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/7.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/8.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/9.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/10.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/11.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/12.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/13.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/14.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/15.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/16.jpg' },
        { type: 'image', src: '/images/projects/romacratermundi/still2.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still3.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still4.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still5.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still6.png' },
        { type: 'image', src: '/images/projects/romacratermundi/still7.png' }
    ]
},

{
    id: 'one-of-these-days',
    title: 'ONE OF THESE DAYS',
    year: 2023,
    categories: ['Video & Motion Design'],
    description: 'Un tributo visivo al celebre brano dei Pink Floyd, realizzato interamente animando in After Effects disegni creati su Illustrator. Il video esplora un\'estetica "flat", basata su ripetizioni grafiche, giochi di sovrapposizione con metodi di fusione (come "differenza") e un montaggio serrato che segue in modo quasi ossessivo il ritmo e la struttura della musica.',
    shortDescription: 'Tributo animato al brano dei Pink Floyd, caratterizzato da un\'estetica flat, animazioni ritmiche e un montaggio sincronizzato con la musica.',
    image: '/images/projects/oneofthesedays/10.png' ,
    link: '/works/one-of-these-days',
    heroMedia: { type: 'youtube', videoId: 'MS6i-Be5YXg' },
    technologies: ['Adobe After Effects', 'Adobe Illustrator'],
    keyFeatures: [
        'Animazione 2D basata su grafica vettoriale.',
        'Stile visivo "flat" con uso creativo dei livelli.',
        'Montaggio video strettamente sincronizzato con la traccia musicale.',
        'Uso di effetti di ripetizione e metodi di fusione per creare pattern complessi.',
        'Interpretazione visiva di un classico della musica rock.'
    ],
    challenge: 'La sfida era tradurre la potenza e l\'atmosfera del brano dei Pink Floyd in un linguaggio visivo coerente, senza essere didascalici. L\'obiettivo era creare un flusso visivo che completasse la musica, mantenendo alta l\'attenzione attraverso la ripetizione e la variazione.',
    solution: 'Utilizzando forme geometriche semplici e una palette di colori limitata, l\'animazione si concentra sul movimento e sul ritmo. La sincronia tra audio e video è stata la chiave per costruire la tensione, mentre l\'uso dei livelli in "differenza" ha permesso di creare variazioni visive inaspettate, rispecchiando la natura sperimentale del brano.',
    gallery: [{ type: 'image', src: '/images/projects/oneofthesedays/1.png' },
        { type: 'image', src: '/images/projects/oneofthesedays/2.png' },
        { type: 'image', src: '/images/projects/oneofthesedays/3.png' },
        { type: 'image', src: '/images/projects/oneofthesedays/4.png' },
        { type: 'image', src: '/images/projects/oneofthesedays/5.png' },
        { type: 'image', src: '/images/projects/oneofthesedays/6.png' },
        { type: 'image', src: '/images/projects/oneofthesedays/7.png' },
        { type: 'image', src: '/images/projects/oneofthesedays/8.png' },
        { type: 'image', src: '/images/projects/oneofthesedays/9.png' },
        { type: 'image', src: '/images/projects/oneofthesedays/10.png' }
    ]
},

{
    id: 'friends-in-my-head',
    title: 'FRIENDS IN MY HEAD',
    year: 2025,
    categories: ['Video & Motion Design', 'Direzione Creativa & Art Direction'],
    description: 'Un cortometraggio diretto e girato in una sola ora come sfida creativa, partendo da quattro parole generate casualmente: caccia, voci, acqua, follia. Il film segue la discesa nella psicosi di un ragazzo affetto da schizofrenia, che si avventura in una riserva di caccia. La narrazione visiva, volutamente amatoriale e delirante, è caratterizzata da uno stile in bianco e nero e un montaggio serrato che riflette il progressivo crollo mentale del protagonista, fino a un tragico epilogo.',
    shortDescription: 'Cortometraggio sperimentale su un ragazzo schizofrenico, girato in un\'ora e basato su parole casuali, con uno stile delirante in bianco e nero.',
    image: '/images/projects/friendsinmyhead/still4.png',
    link: '/works/friends-in-my-head',
    heroMedia: { type: 'vimeo', videoId: '1097622993' },
    technologies: ['Adobe After Effects', 'DaVinci Resolve'],
    keyFeatures: [
        'Progetto realizzato con un vincolo di tempo stringente (1 ora).',
        'Narrazione basata su input creativi casuali.',
        'Regia e montaggio che riflettono uno stato mentale alterato.',
        'Stile visivo in bianco e nero volutamente grezzo e amatoriale.',
        'Esplorazione del tema della malattia mentale attraverso il video.'
    ],
    challenge: 'La sfida principale era costruire una narrazione coerente e di impatto partendo da concetti slegati e con un tempo di produzione estremamente limitato. L\'obiettivo era trasmettere la sensazione di follia e delirio non solo attraverso la storia, ma anche con lo stile di ripresa e montaggio.',
    solution: 'Abbracciando i vincoli come elementi stilistici, il risultato è un cortometraggio viscerale. La camera a mano, il montaggio rapido e l\'estetica in bianco e nero a basso contrasto contribuiscono a creare un\'atmosfera opprimente e caotica, immergendo lo spettatore nella prospettiva disturbata del protagonista.',
    gallery: [{ type: 'image', src: '/images/projects/friendsinmyhead/still1.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still2.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still3.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still4.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still5.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still6.png' },
        { type: 'image', src: '/images/projects/friendsinmyhead/still7.png' }
    ]
},

// --- NUOVI PROGETTI DA COMPILARE ---
/*

{
    id: 'haizum',
    title: 'HAIZUM',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/haizum.png',
    link: '/works/haizum',
    heroMedia: { type: 'image', src: '/images/hero/haizum.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/haizum/1.png' }]
},
{
    id: 'il-viaggio-nel-linguaggio',
    title: 'IL VIAGGIO NEL LINGUAGGIO',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/il-viaggio-nel-linguaggio.png',
    link: '/works/il-viaggio-nel-linguaggio',
    heroMedia: { type: 'image', src: '/images/hero/il-viaggio-nel-linguaggio.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/il-viaggio-nel-linguaggio/1.png' }]
},
{
    id: 'trashfinder',
    title: 'TRASHFINDER',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/trashfinder.png',
    link: '/works/trashfinder',
    heroMedia: { type: 'image', src: '/images/hero/trashfinder.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/trashfinder/1.png' }]
},
{
    id: 'algorithmube',
    title: 'ALGORITHMUBE',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/algorithmube.png',
    link: '/works/algorithmube',
    heroMedia: { type: 'image', src: '/images/hero/algorithmube.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/algorithmube/1.png' }]
},
{
    id: 'subviral',
    title: 'SUBVIRAL',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/subviral.png',
    link: '/works/subviral',
    heroMedia: { type: 'vimeo', videoId: '1093522831' },
    figmaEmbedUrl: "https://embed.figma.com/proto/k0GTgBcvxZax45PHgdhmGG/KOLLATERAL-%7C-SUBVIRAL?page-id=186%3A115&node-id=186-353&viewport=482%2C221%2C0.18&scaling=contain&content-scaling=fixed&embed-host=share",
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/subviral/1.png' }]
},
{
    id: 'templarave',
    title: 'TEMPLARAVE',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/templarave.png',
    link: '/works/templarave',
    heroMedia: { type: 'image', src: '/images/hero/templarave.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/templarave/1.png' }]
},
{
    id: 'topology-of-decay',
    title: 'TOPOLOGY OF DECAY',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/topology-of-decay.png',
    link: '/works/topology-of-decay',
    heroMedia: { type: 'image', src: '/images/hero/topology-of-decay.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/topology-of-decay/1.png' }]
},
{
    id: 'y2kmush',
    title: 'Y2KMUSH',
    year: 2025,
    categories: ['Placeholder'],
    description: 'Descrizione completa da inserire.',
    shortDescription: 'Descrizione breve da inserire.',
    image: '/images/cards/y2kmush.png',
    link: '/works/y2kmush',
    heroMedia: { type: 'image', src: '/images/hero/y2kmush.png' },
    technologies: ['Tecnologia 1'],
    keyFeatures: ['Caratteristica 1'],
    challenge: 'Sfida da inserire.',
    solution: 'Soluzione da inserire.',
    gallery: [{ type: 'image', src: '/images/gallery/y2kmush/1.png' }]
}
    */
];

// Function to get a work by its ID
export function getWorkById(id) {
    return worksData.find(work => work.id === id);
}